version: '3.8'

services:
  app:
    image: jamesgm/archer1600vapi:latest
    ports:
      - "3000:3000"
    environment:
      - ROUTER_USERNAME=${ROUTER_USERNAME}
      - ROUTER_PASSWORD=${ROUTER_PASSWORD}
      - ROUTER_API_BASE_URL=${ROUTER_API_BASE_URL}
